/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ThinkEasy
 * Test Task BE
 * OpenAPI spec version: 1.0
 */
import type {PostResponceAuthor} from './postResponceAuthor'
import type {PostResponceContent} from './postResponceContent'

export interface PostResponce {
  title: string
  content: PostResponceContent
  published: boolean
  author: PostResponceAuthor
}
