/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ThinkEasy
 * Test Task BE
 * OpenAPI spec version: 1.0
 */
import type {CreatePostInput, PostResponce, PostResponse} from '.././_models'
import {axiosInstance} from '.././axios'

export const getPosts = () => {
  /**
   * @summary Create a new post
   */
  const postsControllerCreate = (createPostInput: CreatePostInput) => {
    return axiosInstance<PostResponce>({
      url: '/posts',
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      data: createPostInput,
    })
  }
  /**
   * @summary Get all posts
   */
  const postsControllerGetAllPosts = () => {
    return axiosInstance<PostResponse[]>({url: '/posts', method: 'GET'})
  }
  /**
   * @summary Get all posts of a user
   */
  const postsControllerUserPosts = (userId: string) => {
    return axiosInstance<PostResponse[]>({
      url: `/posts/user/${userId}`,
      method: 'GET',
    })
  }
  /**
   * @summary Get a post by its ID
   */
  const postsControllerPost = (postId: string) => {
    return axiosInstance<PostResponse>({url: `/posts/${postId}`, method: 'GET'})
  }
  return {
    postsControllerCreate,
    postsControllerGetAllPosts,
    postsControllerUserPosts,
    postsControllerPost,
  }
}
export type PostsControllerCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPosts>['postsControllerCreate']>>
>
export type PostsControllerGetAllPostsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPosts>['postsControllerGetAllPosts']>>
>
export type PostsControllerUserPostsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPosts>['postsControllerUserPosts']>>
>
export type PostsControllerPostResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPosts>['postsControllerPost']>>
>
